apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-deployment
  namespace: develop
  labels:
    role: go-app
spec:
  replicas: 2
  selector:
    matchLabels:
      role: go-app
  template:
    metadata:
      labels:
        role: go-app
    spec:
      containers:
      - name: go-app
        image: ""
        resources:
          requests:
            cpu: 10m

