apiVersion: v1
kind: Service
metadata:
  name: hello-svc
  namespace: develop
spec:
  type: NodePort
  selector:
    role: go-app
  ports:
    - port: 8080
      targetPort: 8080
      name: http
      

