apiVersion: v1
kind: Service
metadata:
  name: hello-svc
  namespace: develop
spec:
  selector:
    role: go-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 32000
  type: NodePort
